name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH Deploy
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/2405029_CI-CD/blog-cms-main
          
          # Ambil kode terbaru
          git pull origin main
          
          # Update library & Build Aset (PENTING untuk tampilan)
          composer install --no-dev --optimize-autoloader
          npm install
          npm run build
          
          # Bersihkan semua ingatan lama Laravel
          php artisan migrate --force
          php artisan optimize:clear
          php artisan view:clear
          php artisan cache:clear
          php artisan config:clear
          php artisan optimize